# Generated by Django 3.1 on 2020-09-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roshan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('projecttype', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=200)),
                ('preview', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
