# Generated by Django 3.1 on 2020-09-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roshan', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('name', models.CharField(default='', max_length=50)),
                ('presentedby', models.CharField(default='', max_length=50)),
                ('desc', models.TextField()),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
